settings:
  # Language: en or vi
  language: en
  # Can the mace be dropped by the player?
  allow-drop: true
  # Tracking mode: Strict Mode
  # If true: Player CANNOT drop the Mace or put it in any container (Chest, etc.).
  # Player CAN still use Anvil and Enchanting Table.
  strict-mode: false

mace:
  name: "&b&lMACE OF POWER"
  material: MACE
  custom-model-data: 2001
  lore:
    - "&7An ancient weapon."
    - "&7Hold to charge power."
    - "&7&oOnly one can exist."
  
  # Recipe for the Power Mace
  recipe:
    enabled: true
    shape:
      - " H "
      - " I "
      - " B "
    ingredients:
      H: HEAVY_CORE
      I: NETHERITE_INGOT
      B: BREEZE_ROD
